use std::borrow::Cow;
use std::sync::Arc;

use playroom::{HostMessage, RoomEvent};
use rmcp::model::*;
use rmcp::service::RequestContext;
use rmcp::{ErrorData, Peer, RoleServer, ServerHandler};
use serde_json::Value;
use tokio::sync::{mpsc, Mutex};

use crate::service::{AppError, AppEvent, AppService, AppState};

pub struct PlaytableMcpHandler {
    service: Arc<AppService>,
    /// AppEvent 受信側。initialize 時に purge タスクへ渡す。
    event_rx: Mutex<Option<mpsc::Receiver<AppEvent>>>,
    peer: Mutex<Option<Peer<RoleServer>>>,
}

impl PlaytableMcpHandler {
    pub fn new(service: Arc<AppService>, event_rx: mpsc::Receiver<AppEvent>) -> Self {
        Self {
            service,
            event_rx: Mutex::new(Some(event_rx)),
            peer: Mutex::new(None),
        }
    }

    async fn set_peer(&self, peer: Peer<RoleServer>) {
        *self.peer.lock().await = Some(peer);
    }

    async fn peer(&self) -> Option<Peer<RoleServer>> {
        self.peer.lock().await.clone()
    }

    /// AppEvent を MCP の logging / tool_list_changed に変換する常駐タスクを起動する。
    async fn start_event_forwarder(self: Arc<Self>) {
        let Some(mut rx) = self.event_rx.lock().await.take() else {
            return;
        };
        let this = self.clone();
        tokio::spawn(async move {
            while let Some(event) = rx.recv().await {
                this.forward_event(event).await;
            }
        });
    }

    async fn forward_event(&self, event: AppEvent) {
        let peer = match self.peer().await {
            Some(p) => p,
            None => return,
        };

        match event {
            AppEvent::Room(ev) => {
                let msg = format_room_event(&ev);
                notify_log(&peer, &msg).await;
            }
            AppEvent::Guest(msg) => {
                if let Some(text) = format_host_message(&msg) {
                    notify_log(&peer, &text).await;
                }
            }
            AppEvent::StateChanged(_) => {
                let _ = peer.notify_tool_list_changed().await;
            }
        }
    }

    fn tools_for_state(state: &AppState) -> Vec<Tool> {
        match state {
            AppState::Uninitialized => vec![
                make_tool(
                    "create_user",
                    "Create a new user identity. Generates a fresh Ed25519 keypair and registers the given user_id.",
                    json_schema_obj(&[(
                        "user_id",
                        "string",
                        "Alphanumeric 1-32 chars. Your chosen identifier.",
                    )]),
                ),
                make_tool(
                    "pair_device",
                    "Adopt an existing user identity from another device. Uses an invite code generated by pair_init on the existing device.",
                    json_schema_obj(&[
                        (
                            "invite_code",
                            "string",
                            "77-character Base32 invite from the existing device",
                        ),
                        (
                            "device_label",
                            "string",
                            "Label for this device (e.g. 'Laptop')",
                        ),
                    ]),
                ),
            ],
            AppState::MainMenu => vec![
                make_tool("list_rooms", "List rooms hosted by friends", json_schema_empty()),
                make_tool(
                    "create_room",
                    "Create and host a new room",
                    json_schema_obj(&[("name", "string", "Room name")]),
                ),
                make_tool(
                    "join_room",
                    "Join a friend's room (by user_id or user public key hex prefix)",
                    json_schema_obj(&[("friend", "string", "Friend user_id or key prefix")]),
                ),
                make_tool("list_friends", "List registered friends", json_schema_empty()),
                make_tool(
                    "add_friend",
                    "Add a friend by EndpointId. The friend's identity is fetched via QueryRoom.",
                    json_schema_obj(&[(
                        "endpoint_id",
                        "string",
                        "Hex-encoded EndpointId (64 hex chars)",
                    )]),
                ),
                make_tool("list_devices", "List your own paired devices", json_schema_empty()),
                make_tool(
                    "pair_init",
                    "Generate an invite code that another device (new) can use to adopt this identity. Window expires in 120s.",
                    json_schema_empty(),
                ),
                make_tool(
                    "sync_device",
                    "Sync friends/devices with another of your own devices.",
                    json_schema_obj(&[(
                        "endpoint_id",
                        "string",
                        "Hex-encoded EndpointId of your other device",
                    )]),
                ),
            ],
            AppState::InRoomHost | AppState::InRoomGuest => vec![
                make_tool(
                    "send_message",
                    "Send a chat message to the room",
                    json_schema_obj(&[("content", "string", "Message content")]),
                ),
                make_tool("leave_room", "Leave the current room", json_schema_empty()),
            ],
        }
    }

    async fn handle_create_user(&self, args: &Value) -> Result<CallToolResult, ErrorData> {
        let user_id = require_str(args, "user_id")?;
        let result = self.service.create_user(user_id).await.map_err(map_err)?;
        Ok(ok_text(format!(
            "User created.\nuser_id: {}\nuser_public_key: {}\nEndpointId: {}",
            result.user_id,
            hex::encode(result.user_public_key),
            hex::encode(result.endpoint_id),
        )))
    }

    async fn handle_pair_device(&self, args: &Value) -> Result<CallToolResult, ErrorData> {
        let invite_code = require_str(args, "invite_code")?;
        let device_label = args
            .get("device_label")
            .and_then(|v| v.as_str())
            .unwrap_or("New Device");

        let result = self
            .service
            .pair_device(invite_code, device_label)
            .await
            .map_err(map_err)?;
        Ok(ok_text(format!(
            "Paired successfully.\nuser_id: {}\nuser_public_key: {}\nDevice labeled '{}'.",
            result.user_id,
            hex::encode(result.user_public_key),
            result.device_label,
        )))
    }

    async fn handle_list_rooms(&self) -> Result<CallToolResult, ErrorData> {
        let listing = self.service.list_rooms().await.map_err(map_err)?;
        let text = if listing.rooms.is_empty() {
            "No rooms found.".to_string()
        } else {
            let lines: Vec<String> = listing
                .rooms
                .iter()
                .map(|r| {
                    format!(
                        "[{}] {} ({} members: {})",
                        r.friend_display,
                        r.room_name,
                        r.members.len(),
                        r.members.join(", ")
                    )
                })
                .collect();
            format!("Available rooms:\n{}", lines.join("\n"))
        };
        Ok(ok_text(text))
    }

    async fn handle_create_room(&self, args: &Value) -> Result<CallToolResult, ErrorData> {
        let name = args.get("name").and_then(|v| v.as_str()).unwrap_or("My Room");
        let created = self.service.create_room(name).await.map_err(map_err)?;
        Ok(ok_text(format!(
            "Room '{}' created! Your EndpointId: {}",
            created.name,
            hex::encode(created.endpoint_id),
        )))
    }

    async fn handle_join_room(&self, args: &Value) -> Result<CallToolResult, ErrorData> {
        let friend = require_str(args, "friend")?;
        let joined = self.service.join_room(friend).await.map_err(map_err)?;
        let entries: Vec<(String, playroom::UserPublicKey)> = joined
            .members
            .iter()
            .map(|m| (m.user_id.clone(), m.user_public_key))
            .collect();
        let members = entries
            .iter()
            .map(|(id, pk)| playroom::identity::with_key_suffix(id, pk))
            .collect::<Vec<_>>()
            .join(", ");
        Ok(ok_text(format!(
            "Joined room '{}'! Members: {members}",
            joined.room_name
        )))
    }

    async fn handle_list_friends(&self) -> Result<CallToolResult, ErrorData> {
        let listing = self.service.list_friends().await.map_err(map_err)?;
        if listing.friends.is_empty() {
            return Ok(ok_text("No friends registered."));
        }
        let mut lines = vec!["Friends:".to_string()];
        for f in &listing.friends {
            lines.push(format!(
                "  {}",
                playroom::identity::with_key_suffix(&f.user_id, &f.user_public_key)
            ));
        }
        Ok(ok_text(lines.join("\n")))
    }

    async fn handle_add_friend(&self, args: &Value) -> Result<CallToolResult, ErrorData> {
        let endpoint_id = require_str(args, "endpoint_id")?;
        let info = self.service.add_friend(endpoint_id).await.map_err(map_err)?;
        Ok(ok_text(format!("Friend '{}' added.", info.user_id)))
    }

    async fn handle_list_devices(&self) -> Result<CallToolResult, ErrorData> {
        let listing = self.service.list_devices().await.map_err(map_err)?;
        if listing.devices.is_empty() {
            return Ok(ok_text(
                "No devices registered. Use pair_init / pair_device to pair your devices.",
            ));
        }
        let mut lines = vec!["Your devices:".to_string()];
        for d in &listing.devices {
            lines.push(format!("  {} (#{})", d.label, d.endpoint_id_short));
        }
        Ok(ok_text(lines.join("\n")))
    }

    async fn handle_pair_init(&self) -> Result<CallToolResult, ErrorData> {
        let result = self.service.pair_init().await.map_err(map_err)?;
        Ok(ok_text(format!(
            "Pairing window open for {}s.\nOn the new device, run pair_device with:\n  invite_code: {}",
            result.ttl_secs, result.invite_code,
        )))
    }

    async fn handle_sync_device(&self, args: &Value) -> Result<CallToolResult, ErrorData> {
        let endpoint_id = require_str(args, "endpoint_id")?;
        let result = self.service.sync_device(endpoint_id).await.map_err(map_err)?;
        let msg = if result.changed {
            "Sync completed with changes."
        } else {
            "Sync completed (no changes)."
        };
        Ok(ok_text(msg))
    }

    async fn handle_send_message(&self, args: &Value) -> Result<CallToolResult, ErrorData> {
        let content = require_str(args, "content")?;
        self.service.send_message(content).await.map_err(map_err)?;
        Ok(ok_text("Message sent."))
    }

    async fn handle_leave_room(&self) -> Result<CallToolResult, ErrorData> {
        let was_host = self.service.state().await == AppState::InRoomHost;
        self.service.leave_room().await.map_err(map_err)?;
        Ok(ok_text(if was_host {
            "Room closed."
        } else {
            "Left the room."
        }))
    }
}

impl ServerHandler for PlaytableMcpHandler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_tool_list_changed()
                .enable_logging()
                .build(),
        )
        .with_server_info(Implementation::new("playtable", env!("CARGO_PKG_VERSION")))
        .with_instructions(
            "Playroom: P2P multiplayer rooms with chat. If uninitialized, call create_user or pair_device first.",
        )
    }

    fn initialize(
        &self,
        request: InitializeRequestParams,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<InitializeResult, ErrorData>> + Send + '_ {
        async move {
            context.peer.set_peer_info(request);
            self.set_peer(context.peer.clone()).await;
            // event forwarder を起動（冪等）
            // self は &self なので Arc に戻すために一旦この経路は取れない。
            // 代わりに initialize 時にグローバルに1回だけ起動する仕組みを作る。
            Ok(self.get_info())
        }
    }

    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListToolsResult, ErrorData>> + Send + '_ {
        async move {
            let state = self.service.state().await;
            let tools = Self::tools_for_state(&state);
            Ok(ListToolsResult {
                tools,
                next_cursor: None,
                meta: None,
            })
        }
    }

    fn call_tool(
        &self,
        request: CallToolRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<CallToolResult, ErrorData>> + Send + '_ {
        async move {
            let name: &str = &request.name;
            let args = request
                .arguments
                .as_ref()
                .map(|a| serde_json::Value::Object(a.clone().into_iter().collect()))
                .unwrap_or(serde_json::Value::Null);

            match name {
                "create_user" => self.handle_create_user(&args).await,
                "pair_device" => self.handle_pair_device(&args).await,
                "list_rooms" => self.handle_list_rooms().await,
                "create_room" => self.handle_create_room(&args).await,
                "join_room" => self.handle_join_room(&args).await,
                "list_friends" => self.handle_list_friends().await,
                "add_friend" => self.handle_add_friend(&args).await,
                "list_devices" => self.handle_list_devices().await,
                "pair_init" => self.handle_pair_init().await,
                "sync_device" => self.handle_sync_device(&args).await,
                "send_message" => self.handle_send_message(&args).await,
                "leave_room" => self.handle_leave_room().await,
                _ => Err(ErrorData::method_not_found::<CallToolRequestMethod>()),
            }
        }
    }

    fn get_tool(&self, _name: &str) -> Option<Tool> {
        None
    }
}

// ── Helpers ──

fn require_str<'a>(args: &'a Value, key: &str) -> Result<&'a str, ErrorData> {
    args.get(key)
        .and_then(|v| v.as_str())
        .ok_or_else(|| ErrorData::invalid_params(format!("{key} is required"), None))
}

fn map_err(e: AppError) -> ErrorData {
    match e {
        AppError::InvalidArg(s) => ErrorData::invalid_params(s, None),
        AppError::NotInitialized | AppError::AlreadyInitialized | AppError::NotInRoom => {
            ErrorData::invalid_params(e.to_string(), None)
        }
        AppError::Internal(s) => ErrorData::internal_error(s, None),
    }
}

fn ok_text<S: Into<String>>(s: S) -> CallToolResult {
    CallToolResult::success(vec![Content::text(s.into())])
}

async fn notify_log(peer: &Peer<RoleServer>, message: &str) {
    let _ = peer
        .notify_logging_message(LoggingMessageNotificationParam {
            level: LoggingLevel::Info,
            logger: Some("playroom".to_string()),
            data: serde_json::json!(message),
        })
        .await;
}

fn format_room_event(event: &RoomEvent) -> String {
    match event {
        RoomEvent::MemberJoined { user_id, .. } => format!("* {user_id} joined the room"),
        RoomEvent::MemberLeft { user_id, .. } => format!("* {user_id} left the room"),
        RoomEvent::ChatReceived { from, content } => format!("[chat] {from}: {content}"),
        RoomEvent::RoomCreated { name } => format!("* Room '{name}' created"),
        RoomEvent::RoomClosed => "* Room closed".to_string(),
        RoomEvent::PairingWindowOpened => "* Pairing window opened".to_string(),
        RoomEvent::PairingWindowClosed => "* Pairing window closed".to_string(),
        RoomEvent::PairingCompleted { device_label, .. } => {
            format!("* Paired with new device: {device_label}")
        }
        RoomEvent::SyncCompleted { .. } => "* Sync completed".to_string(),
    }
}

fn format_host_message(msg: &HostMessage) -> Option<String> {
    match msg {
        HostMessage::Chat { from, content } => Some(format!("[chat] {from}: {content}")),
        HostMessage::MemberJoined(info) => Some(format!("* {} joined the room", info.user_id)),
        HostMessage::MemberLeft { user_id, .. } => Some(format!("* {user_id} left the room")),
        HostMessage::RoomClosed => Some("* Room has been closed by the host".to_string()),
        HostMessage::Rejected { reason } => Some(format!("Rejected: {reason}")),
        _ => None,
    }
}

fn make_tool(name: &str, description: &str, input_schema: Arc<JsonObject>) -> Tool {
    let mut tool = Tool::default();
    tool.name = Cow::Owned(name.to_string());
    tool.description = Some(Cow::Owned(description.to_string()));
    tool.input_schema = input_schema;
    tool
}

fn json_schema_empty() -> Arc<JsonObject> {
    Arc::new(
        serde_json::from_value(serde_json::json!({
            "type": "object",
            "properties": {}
        }))
        .unwrap(),
    )
}

fn json_schema_obj(props: &[(&str, &str, &str)]) -> Arc<JsonObject> {
    let mut properties = serde_json::Map::new();
    let mut required = Vec::new();
    for (name, typ, desc) in props {
        properties.insert(
            name.to_string(),
            serde_json::json!({
                "type": typ,
                "description": desc,
            }),
        );
        required.push(serde_json::Value::String(name.to_string()));
    }
    Arc::new(
        serde_json::from_value(serde_json::json!({
            "type": "object",
            "properties": properties,
            "required": required,
        }))
        .unwrap(),
    )
}

/// `run()` から Arc<handler> を使って forwarder を起動できるようにする公開ヘルパー。
impl PlaytableMcpHandler {
    pub async fn spawn_forwarder(self: &Arc<Self>) {
        self.clone().start_event_forwarder().await;
    }
}
