[package]
name = "playroom"
version = "0.1.0"
edition = "2021"

[dependencies]
iroh = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
bytes = "1"
